### PR TITLE
extend multipage handling

### PR DESCRIPTION
**Pull request by tb102122**
*Issue:* #94, #92

*Description of changes:* 
1. add handling for of functions for multipage documents.
2. add depreciation warning for find_phrase_in_lines

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tb102122** [comment]
@schadem would it be possible to merge the PR in the near future?

**Comment by tb102122** [comment]
@schadem can you merge this one as well i would need it for my next release

**Comment by tb102122** [comment]
@schadem please release this as well

**Comment by tb102122** [comment]
@alexrudd2 Can you release that fix as well?

**Comment by alexrudd2** [comment]
> @alexrudd2 Can you release that fix as well?

Not my repo :)

**Comment by schadem** [comment]
Should have more time now after releasing https://github.com/aws-samples/amazon-textract-idp-cdk-constructs and https://github.com/aws-samples/amazon-textract-idp-cdk-stack-samples...

**Pull request merged**
