### PR TITLE
upgrade versions and dependency

### PR DESCRIPTION
**Pull request by tb102122**
*Issue #, 
https://github.com/aws-samples/amazon-textract-textractor/issues/254

https://github.com/aws-samples/amazon-textract-textractor/issues/253

*Description of changes:* Update of module dependancy and versions

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tb102122** [comment]
@Belval Do you think we can release this PR?
It blocks one of my projects at the moment.

**Review by Belval — APPROVED** [review]

**Comment by tb102122** [comment]
Anything you like me to change?

**Comment by Belval** [comment]
No, it was good to merge, thank you.

**Comment by tb102122** [comment]
@Belval sorry to follow up once again. For some reason I don't see the new version published: https://pypi.org/project/amazon-textract-overlayer/ any idea why?

**Comment by tb102122** [comment]
@Belval Do you have any feedback for me? Should I great a new issue for it?

**Comment by tb102122** [comment]
@Belval @schadem sorry to ask again but when do you think can you fix the release process for the above name modules?

**Pull request merged**
