### PR TITLE
add page_no

### PR DESCRIPTION
**Pull request by tb102122**
*Description of changes:* add page number to page class to simplefy the iteration for drawing bounding boxes and searches.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tb102122** [comment]
the formatter is enabled but some if the setting are missing or?

**Comment by tb102122** [comment]
@schadem Do I have to update the change also in the following main class?
https://github.com/aws-samples/amazon-textract-response-parser/blob/master/src-python/trp/__init__.py in line 435ff?

**Comment by tb102122** [comment]
@schadem when do you think are you free again to look into these open PRs?

**Comment by schadem** [comment]
Sorry, back from vacation. Can you reformat so that only the actual relevant changes are visible in the diff? Hard to make out the actual difference/addition.

**Comment by tb102122** [comment]
> Sorry, back from vacation. Can you reformat so that only the actual relevant changes are visible in the diff? Hard to make out the actual difference/addition.

I tried to reformat some parts but somehow the format settings are not used correctly in my VS Code.

**Comment by tb102122** [comment]
> @schadem Do I have to update the change also in the following main class? https://github.com/aws-samples/amazon-textract-response-parser/blob/master/src-python/trp/__init__.py in line 435ff?

Please also let me know if this update is needed. Hope you enjoyed your vacation.

**Comment by tb102122** [comment]
@schadem When do you think can you more the changes?

**Comment by tb102122** [comment]
@schadem can you please merge or is there any chance you require me to do?

**Comment by tb102122** [comment]
@schadem can you merge this update?

**Comment by schadem** [comment]
old stuff one, probably going to delete the src folder soon... You probably know the best where to grab the actual textract-response-parser

**Pull request merged**
